name: org-stars-badge
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"  # every 6h

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Auth GH CLI
        run: echo "${{ secrets.ORG_TOKEN }}" | gh auth login --with-token
      - name: Compute total stars
        id: stars
        env:
          ORG: ModioStudio
        run: |
          # sum stargazers_count over all repos (public + private if token allows)
          TOTAL=$(gh api -H "X-GitHub-Api-Version: 2022-11-28" /orgs/$ORG/repos --paginate -q '.[].stargazers_count' | awk '{s+=$1} END{print s+0}')
          echo "total=$TOTAL" >> $GITHUB_OUTPUT
      - name: Publish badge json to Gist
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: GIST_ID_HERE
          filename: org-stars.json
          label: Stars
          message: ${{ steps.stars.outputs.total }}
          color: yellow
